{% extends "header.html" %}

{% block body %}

<style>
hr {
    color: blue;
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 10px;
}
</style>

    <br><br><br><h1 style="text-align: center;"><img style="max-width: 175px; margin-top: -10px; " src="{{url_for('static', filename='photos/c_sharp.png') }}">
    Welcome to the C# Exceptions Homepage, mate!</h1>

    <hr>

    <blockquote>

        C# Exceptions Information

    </blockquote>
<style>
.code
{
	background-color: #E0FFFF;
}
.output
{
	background-color: #000000;
	color: #ffffff;
}
h1
{
	text-align: center;
	text-decoration: underline;
}
h2
{
	text-decoration: underline;
}
.content
{
	text-align: center;
}
table
{
background-color: #6495ed;
color: #ffffff;
border: solid 2px black;
}
</style>
<p>An <b>exception</b> is a problem that arises during the execution of a program. A C# exception is a response to an abnormal circumstance that arises while a program is running.
</br>For instance dividing by zero would fit this criteria.</p>
<p>Exceptions provide a way to transfer control from one part of a program to another. C# exception handling is built upon four keywords: <strong>try</strong>, <strong>catch</strong>, <strong>finally</strong>, and <strong>throw</strong>.</p>
<ul class="list">
<li>
<p><strong>try</strong>: A try block identifies a block of code for which particular exceptions is activated. It is followed by one or more catch blocks.</p>
</li>
<li>
<p><strong>catch</strong>: A program catches an exception with an exception handler at the place in a program where you want to handle the problem. The catch keyword indicates the catching of an exception.</p>
</li>
<li>
<p><strong>finally</strong>: The finally block is used to execute a given set of statements, whether an exception is thrown or not thrown. For example, if you open a file, it must be closed whether an exception is raised or not.</p>
</li>
<li>
<p><strong>throw</strong>: A program throws an exception when a problem shows up. This is done using a throw keyword.</p>
</li>
</ul>
<h2>Exceptions Syntax</h2>
<p>Assuming a block raises an exception, a method catches an exception using a combination of the try and catch keywords. A try/catch block is placed around the code that might generate an exception. Code within a try/catch block is referred to as protected code, and the syntax for using try/catch looks like the following:</p>
<div class="code">
<pre class="prettyprint notranslate prettyprinted"><span class="kwd">try</span>
<span class="pun">{</span>
   <span class="com">// statements causing exception</span>
<span class="pun">}</span>
<span class="kwd">catch</span><span class="pun">(</span> <span class="typ">ExceptionName</span><span class="pln"> e1 </span><span class="pun">)</span>
<span class="pun">{</span>
   <span class="com">// error handling code</span>
<span class="pun">}</span>
<span class="kwd">catch</span><span class="pun">(</span> <span class="typ">ExceptionName</span><span class="pln"> e2 </span><span class="pun">)</span>
<span class="pun">{</span>
   <span class="com">// error handling code</span>
<span class="pun">}</span>
<span class="kwd">catch</span><span class="pun">(</span> <span class="typ">ExceptionName</span><span class="pln"> eN </span><span class="pun">)</span>
<span class="pun">{</span>
   <span class="com">// error handling code</span>
<span class="pun">}</span>
<span class="kwd">finally</span>
<span class="pun">{</span>
   <span class="com">// statements to be executed</span>
<span class="pun">}</span></pre>
</div>
<p>You can list down multiple catch statements to catch different type of exceptions in case your try block raises more than one exception in different situations.</p>
<h2>Exception Classes in C#</h2>
<p>C# exceptions are represented by classes. The exception classes in C# are mainly directly or indirectly derived from the <strong>System.Exception</strong> class. Some of the exception classes derived from the System.Exception class are the <strong>System.ApplicationException</strong> and <strong>System.SystemException</strong> classes.</p>
<p>The <strong>System.ApplicationException</strong> class supports exceptions generated by application programs. Hence the exceptions defined by the programmers should derive from this class.</p>
<p>The <strong>System.SystemException</strong> class is the base class for all predefined system exception.</p>
<p>The following table provides some of the predefined exception classes derived from the Sytem.SystemException class:</p>
<table class="table table-bordered">
<tbody>
<tr>
<th>Exception Class</th>
<th>Description</th>
</tr>
<tr>
<td>System.IO.IOException</td>
<td>Handles I/O errors.</td>
</tr>
<tr>
<td>System.IndexOutOfRangeException</td>
<td>Handles errors generated when a method refers to an array index out of range.</td>
</tr>
<tr>
<td>System.ArrayTypeMismatchException</td>
<td>Handles errors generated when type is mismatched with the array type.</td>
</tr>
<tr>
<td>System.NullReferenceException</td>
<td>Handles errors generated from deferencing a null object.</td>
</tr>
<tr>
<td>System.DivideByZeroException</td>
<td>Handles errors generated from dividing a dividend with zero.</td>
</tr>
<tr>
<td>System.InvalidCastException</td>
<td>Handles errors generated during typecasting.</td>
</tr>
<tr>
<td>System.OutOfMemoryException</td>
<td>Handles errors generated from insufficient free memory.</td>
</tr>
<tr>
<td>System.StackOverflowException</td>
<td>Handles errors generated from stack overflow.</td>
</tr>
</tbody>
</table>
<h2>Handling Exceptions</h2>
<p>C# provides a structured solution to the exception handling in the form of try and catch blocks. Using these blocks the core program statements are separated from the error-handling statements.</p>
<p>These error handling blocks are implemented using the <strong>try</strong>, <strong>catch</strong>, and <strong>finally</strong> keywords. Following is an example of throwing an exception when dividing by zero condition occurs:</p>
<div class="code">
<p>
</br>using System;
</br>namespace ErrorHandlingApplication
</br>{
 </br>  class DivNumbers
 </br>  {
  </br>    int result;
  </br>    DivNumbers()
 </br>     {
  </br>       result = 0;
  </br>    }
  </br>    public void division(int num1, int num2)
  </br>    {
  </br>       try
  </br>       {
   </br>         result = num1 / num2;
   </br>      }
   </br>      catch (DivideByZeroException e)
   </br>      {
   </br>         Console.WriteLine("Exception caught: {0}", e);
   </br>      }
   </br>      finally
   </br>      {
   </br>         Console.WriteLine("Result: {0}", result);
   </br>      }
   </br>   }
  </br>    static void Main(string[] args)
   </br>   {
   </br>      DivNumbers d = new DivNumbers();
   </br>      d.division(25, 0);
    </br>     Console.ReadKey();
    </br>  }
  </br> }
</br>}
</p>
</div>
<h2>Output</h2>
<div class="output">
<pre class="result notranslate">Exception caught: System.DivideByZeroException: Attempted to divide by zero.
at ...
Result: 0
</div>
</pre>
<h2>Creating User-Defined Exceptions</h2>
<p>You can also define your own exception. User-defined exception classes are derived from the <strong>Exception</strong> class. The following example demonstrates this:</p>
<div class="code">
<pre class="prettyprint notranslate tryit prettyprinted"><span class="kwd">using</span> <span class="typ">System</span><span class="pun">;</span>
<span class="kwd">namespace</span> <span class="typ">UserDefinedException</span>
<span class="pun">{</span>
   <span class="kwd">class</span> <span class="typ">TestTemperature</span>
   <span class="pun">{</span>
      <span class="kwd">static</span> <span class="kwd">void</span> <span class="typ">Main</span><span class="pun">(</span><span class="kwd">string</span><span class="pun">[]</span><span class="pln"> args</span><span class="pun">)</span>
      <span class="pun">{</span>
         <span class="typ">Temperature</span><span class="pln"> temp </span><span class="pun">=</span> <span class="kwd">new</span> <span class="typ">Temperature</span><span class="pun">();</span>
         <span class="kwd">try</span>
         <span class="pun">{</span><span class="pln">
            temp</span><span class="pun">.</span><span class="pln">showTemp</span><span class="pun">();</span>
         <span class="pun">}</span>
         <span class="kwd">catch</span><span class="pun">(</span><span class="typ">TempIsZeroException</span><span class="pln"> e</span><span class="pun">)</span>
         <span class="pun">{</span>
            <span class="typ">Console</span><span class="pun">.</span><span class="typ">WriteLine</span><span class="pun">(</span><span class="str">"TempIsZeroException: {0}"</span><span class="pun">,</span><span class="pln"> e</span><span class="pun">.</span><span class="typ">Message</span><span class="pun">);</span>
         <span class="pun">}</span>
         <span class="typ">Console</span><span class="pun">.</span><span class="typ">ReadKey</span><span class="pun">();</span>
      <span class="pun">}</span>
   <span class="pun">}</span>
<span class="pun">}</span>

<span class="kwd">public</span> <span class="kwd">class</span> <span class="typ">TempIsZeroException</span><span class="pun">:</span> <span class="typ">Exception</span>
<span class="pun">{</span>
   <span class="kwd">public</span> <span class="typ">TempIsZeroException</span><span class="pun">(</span><span class="kwd">string</span><span class="pln"> message</span><span class="pun">):</span> <span class="kwd">base</span><span class="pun">(</span><span class="pln">message</span><span class="pun">)</span>
   <span class="pun">{</span>
   <span class="pun">}</span>
<span class="pun">}</span>

<span class="kwd">public</span> <span class="kwd">class</span> <span class="typ">Temperature</span>
<span class="pun">{</span>
   <span class="kwd">int</span><span class="pln"> temperature </span><span class="pun">=</span> <span class="lit">0</span><span class="pun">;</span>
   <span class="kwd">public</span> <span class="kwd">void</span><span class="pln"> showTemp</span><span class="pun">()</span>
   <span class="pun">{</span>
      <span class="kwd">if</span><span class="pun">(</span><span class="pln">temperature </span><span class="pun">==</span> <span class="lit">0</span><span class="pun">)</span>
      <span class="pun">{</span>
         <span class="kwd">throw</span> <span class="pun">(</span><span class="kwd">new</span> <span class="typ">TempIsZeroException</span><span class="pun">(</span><span class="str">"Zero Temperature found"</span><span class="pun">));</span>
      <span class="pun">}</span>
      <span class="kwd">else</span>
      <span class="pun">{</span>
         <span class="typ">Console</span><span class="pun">.</span><span class="typ">WriteLine</span><span class="pun">(</span><span class="str">"Temperature: {0}"</span><span class="pun">,</span><span class="pln"> temperature</span><span class="pun">);</span>
      <span class="pun">}</span>
   <span class="pun">}</span>
<span class="pun">}</span></pre>
</div>
<h2>Output</h2>
<div class="output">
<pre class="result notranslate">TempIsZeroException: Zero Temperature found
</div>
</pre>
<h2>Throwing Objects</h2>
<p>You can throw an object if it is either directly or indirectly derived from the <strong>System.Exception</strong> class. You can use a throw statement in the catch block to throw the present object as:</p>
<div class="code">
<pre class="prettyprint notranslate prettyprinted"><span class="typ">Catch</span><span class="pun">(</span><span class="typ">Exception</span><span class="pln"> e</span><span class="pun">)</span>
<span class="pun">{</span>
   <span class="pun">...</span>
   <span class="typ">Throw</span><span class="pln"> e
</span><span class="pun">}</span></pre>
</div>
</br>
</br>
<a href="/C_sharp/files_io"><button type="button" class="btn btn-default btn-lg" aria-label="Left Align">
        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> C# - Files & I/O
    </button></a>

    <a href="/C_sharp/final_thoughts"><button type="button" class="btn btn-default btn-lg" style="float: right;">
        C# - Final Thoughts <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
    </button></a>
{% endblock %}